name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log statement
        run: |
          echo "The workflow is running on a tag in the release branch."
